resources:
  - ../../base

namePrefix: dev-

images:
  - name: uiservice
    newTag: latest-dev

patches:
  - target:
      kind: Deployment
      name: ui-deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-deployment
      spec:
        replicas: 1
        template:
          spec:
            containers:
              - name: ui-container
                imagePullPolicy: Always
                env:
                  - name: ENV
                    value: "dev"
