# k8s/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base # Reference the base resources

# Optionally, add environment-specific patches or configurations
patchesStrategicMerge:
  - deployment-patch.yaml # If you have a patch for the deployment
