# k8s/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base # Reference the base resources

patches:
  - target:
      kind: Deployment
      name: ui-app
      version: v1
    path: deployment-patch.yaml
