# deployment.yaml (in k8s/base)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
  labels:
    app: ui-service
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: ui-service
  template:
    metadata:
      labels:
        app: ui-service
    spec:
      containers:
        - name: ui-service-container
          image: docker.io/lexmarkkubernetes/uiservice:latest
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "dev"
            - name: API_URL
              value: "http://api-service.default.svc.cluster.local"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
