apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui-container
          image: lexmarkkubernetes/uiservice-prod:cd635d034443b3599dfc829fd60ebaf3f24e2b8b
          imagePullPolicy: Always
          ports:
            - containerPort: 80
