resources:
  - ../../base/UI

namePrefix: staging-

images:
  - name: uiservice
    newTag: latest-staging

patches:
  - target:
      kind: Deployment
      name: ui-deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-deployment
      spec:
        replicas: 1
        template:
          spec:
            containers:
              - name: ui-container
                env:
                  - name: ENV
                    value: "staging"
