apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uiservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lexmarkCS499/UI_Microservice'
    targetRevision: HEAD
    path: 'manifests/overlays/dev'  # Adjust based on your target environment
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
