apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ui-rollout
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: {duration: "4m"}  # Manual intervention here
        - setWeight: 100
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui-container
          image: lexmarkkubernetes/uiservice-dev:13a9c3c923d91638487419ff0249f989abc5326f
          imagePullPolicy: Always
          ports:
            - containerPort: 80
