apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui-container
          image: lexmarkkubernetes/uiservice-staging:7d6f142646ade5f7328491413363f37bc919fd5a
          imagePullPolicy: Always
          ports:
            - containerPort: 80
