apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui-container
          image: lexmarkkubernetes/uiservice-staging:98d6d5edb99ece33579696b7e8e6d2c716cca5d0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
